import Navbar from "../Navbar/navbar";
import Footer from "../Footer/footer";
import Head from "next/head";

const Layout = (props) => {
  return (
    <div>
      <Head>
        <title>{props.title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      {props.children}
      <footer>
        <Footer />
      </footer>
    </div>
  );
};

export default Layout;
